const books = {
    "How Google Works":["https://amzn.to/3YwOzSS","Work Rules! offers both a philosophy of the new world of work and a blueprint for attracting the most spectacular talent and ensuring the brightest and best prosper. A New York Times and Wall Street Journal BestsellerDaily Telegraph, Huffington Post & Business Insider Top Business Book to Read. One of the best HR books of all time.","Laszlo Bock"],
    "Rituals for Work: 50 Ways to Create Engagement, Shared Purpose, and a Culture that Can Adapt to Change":["https://amzn.to/3Wz4SNj","A book which talks about the power of creative rituals that can make our personal and professional lives more meaningful and rewarding. It shows how rituals can reinforce good habits, motivate personel and professional achievement, and create a common bond between co-workers and build shared values.", "Kursat Ozenc & Margaret Hagan"],
    "The HR Scorecard":["https://amzn.to/3vabBBM","A wonderful book that manages to align the three key aspects for any organization - people, strategy, and performance - into one single framework. Drawing from the authors' ongoing study of nearly 3,000 firms, this book describes a seven-step process for embedding HR systems within the firm's overall strategy what the authors describe as an HR Scorecard--and measuring its activities in terms that line managers and CEOs will find compelling.", "David Ulrich, Brian E. Becker, and Mark Huselid"],
    "The Talent Delusion":["https://amzn.to/3PKC3vh","This book bridges the gap between the psychological science of talent and common real-world talent practices by showcasing the power of data over intuition.It will help readers understand the current problems pertaining employee selection, development and engagement, how to define and evaluate talent, how to detect and inhibit toxic employee behaviors and how to motivate employees to perform to their best.","Tomas Chamorro-Premuzic"],
    "No Rules Rules":["https://amzn.to/3FHerTD","Shortlisted for the 2020 Financial Times & McKinsey Business Book of the Year, this book is by the founder of Netflix Reed Hastings. It highlights the principles that drive Netflix forward - It's time to do things differently. Trust your team. Be radically honest. And never, ever try to please your boss. Use this book to understand how Netflix offers a fundamentally different way to run any organisation, one far more in tune with an ever-changing fast-paced world.", "Reed Hastings & Erin Meyer"],
    "Start with Why":["https://amzn.to/3PLknzi","Start with Why is a global bestseller and the TED Talk based on it is the third most watched of all time. Why are some people and organisations more inventive, pioneering and successful than others? And why are they able to repeat their success again and again?In business, it doesn't matter what you do, it matters WHY you do it. This concept can be leveraged to create the dream workplace also. A wonderful read for anyone who wants to reinvent their workplace.", "Simon Sinek"],
    "HR Disrupted: It’s Time for Something Different":["https://amzn.to/3PGp2CQ","This book talks about the future of HR. It is probably the only book in our list that focuses more on the future than the past. It encourages the readers to look beyond process changes and look into the world of talent with a fresh approach. The book focuses on three approaches - treat employees as adults and not as children, treat employees as consumers or customers and disregard a one-size-fits-all approach, and treat employees as human beings.","Lucy Adams"],
    "Nine Lies About Work: A Freethinking Leader’s Guide to the Real World":["https://amzn.to/3Wxa2JJ","This book turns the accepted notions of corporate world upside down and creates a wonderful view. This book talks about the big lies or distortions that we encounter every time we show up for work. Nine lies about work reveals the few core truths that will help you show just how good you are to those who truly rely on you.","Marcus Buckingham & Ashely Goodall"],
    "Belonging at Work: Everyday Actions You Can Take to Cultivate an Inclusive Organization":["https://amzn.to/3hOmh5L","This book uses a vast set of examples and case studies to share how organizations can cultivate great workplace cultures where all the stakeholders can show up authentically and feel respected for their contributions. A wonderful and inspiring read.", "Rhodes Perry"],
    "Thinking, Fast and Slow":["https://amzn.to/3WxRYyV","An international best seller, this is a great book on human rationality (or the lack of it) & describes how our minds are tripped up by error and prejudice (even when we think we are being logical) and gives practical insights for slower, and smarter thnking. Most of these concepts can be adopted in our day-to-day work in our organizations.","Daniel Kahneman"],
    "The Fearless Organization: Creating Psychological Safety in the Workplace for Learning, Innovation, and Growth":["https://amzn.to/3PKVwMe","A wonderful book that talks about ways in which organizations can create a culture in which knowledge and innovation can thrive. It talks about how organization can drive a culture which does not suppress, ridicule, silence, or intimidate any idea. The books focus on creating a workplace that is safe, fearless, and empowered needs a special mention. Very important because you cannot be afraid in a dream. If you are afraid, it is a nightmare.","Amy C Edmondson"],
    "The Workforce Scorecard: Managing Human Capital to Execute Strategy":["https://amzn.to/3jnhPeZ","This book focuses on one aspect that many organizations forget - the key to success from a talent perspective is to foster and encourage meaningful relationships. The book encourages organizations to foster authenticity, openness, and basic politeness - and apply them day in and day out to their organization's practices. A wonderful read.","Erica Keswin"],
    "Measure What Matters":["https://amzn.to/3Wq8p0m","An international best seller, and probably the definitive guide on OKRs. A widely read book that talks about the concept of OKRs and explains concepts that can be adopted to help adopt the OKR methodology across your organization. A must read. And not just from a talent perspective", "John Doerr"],
    "People Strategy":["https://amzn.to/3FQ6kEa", "A good book on how organizations can build high performing teams, increase employee motivation, and use data to build an inviting and effective company culture. This book focuses on leveraging a value driven culture to create a bedrock of the organizaiton and using the performance feedback and employee engagement processes to drive employee motivation and drive business results. A good read.", "Dana Gaines Robinson"],
    "HR on purpose":["https://amzn.to/3v6WJE2", "A wonderful read that takes us into the future of HR in a manner that is exciting and inspiring. The author talks about everyday aspects in life and relates how HR can relate from that. The books uses real-life examples, insights, and ephiphanies to drop the preconceptions of what HR should be and instead look to what HR could be.", "Steve Browne"],
    "Leaders Eat Last":["https://amzn.to/3vcFnFX","Another gem by Simon Sinek. This books talks about how great leaders and great leadership can inspire people and create environments that foster trust and innovation. Sinek illustrates his ideas with fascinating true stories, from the military to manufacturing, from government to investment banking. He shows that leaders who are willing to eat last are rewarded with deeply loyal colleagues who will stop at nothing to advance their vision. It's amazing how well it works.", "Simon Sinek"],
    "High Growth Handbook":["https://amzn.to/3BTD2n0", "Not your typical HR or talent book, but a brilliant read which talks about the author's personal experience in helping startups scale from a people perspective. Through the book, Gil has identified a set of common patterns and created an accessible playbook for scaling high-growth startups. This includes topics that range from the role of the CEO and the board, to recruiting and overseeing an executive team.", "Elad Gil"],
    "Rework":["https://amzn.to/3hGbRFx","A revolutionary read that may strike you as captivating yet make you question some of the fundamentals that you have imagined so far.Rework is a unique business book which shows the reader a better, faster, easier way to be successful in business. The book tells the reader why plans are truly harmful, why people don't need outside investors and why a person is better ignoring the competition.", "David Heinemeier Hansson & Jason Fried"],
    "Nudge":["https://amzn.to/3WiFrj8", "Probably the most influential book of the 21st century, the book has given rise to the concept of nudges across the world. It has taught us how to use thoughtful choice architecture to help us make better decisions for ourselves, our families, and our society. This final edition offers a wealth of new insights, for both its avowed fans and newcomers, about a wide range of issues that we face in our daily lives -- health, personal finance, climate change, and 'sludge' (paperwork and other nuisances we don't want, and that keep us from getting what we do want) -- all while honouring one of the cardinal rules of nudging: make it fun!","Richard Thaler & Cass Sunstein"],
    "The Culture Code":["https://amzn.to/3v85MVh","An international best-seller, this book reveals the secrets of some of the best teams in the world - from Pixar to Google to US Navy SEALs - explaining the three skills such groups have mastered in order to generate trust and a willingness to collaborate. Combining cutting-edge science, on-the-ground insight and practical ideas for action, it offers a roadmap for creating an environment where innovation flourishes, problems get solved, and expectations are exceeded. As Adam Grant notes,'Well told stories, with actionable lessons'","Daniel Coyle"]
}

module.exports = books;