const themes = {
    "trust": ["Control to Trust & Accountability", 
              "Till a few decades back, managers used to hold the reins of an employee's career. The employees were horses tied to a cart which was driven by their managers and their leadership. Right from granting a leave 'request' to approving an expense approval, managers and the 'higher powers' used to have the final word. This has changed. Right from unlimited vacation days, to a no-question expenses approval policy, employees want to be trusted and be held accountable for their actions and do not believe in the hierarchy of control. They want to be independent and they want to have freedom - to explore, grow up, make mistakes, and learn. They want to be treated as adults, and not as kids.", ],
    "guides": ["Rules to Guides", 
               "Rules are made by the police to make sure that we live in a peaceful society. Rules are also made by schools and academic institutions to ensure that the students stay on track. An organization does not have a police force and is not made up by school kids. An organization is made up of adults, who have the intelligence to make the right decision, mostly. These adults do not need rule books, but guides that advise them on the boundaries that need to be followed, and these adults will stay within that range. Rules control and restrict, guidelines liberate and make room for innovation.",],
    "integration": ["Hiring to Integration", 
                   "In the earlier days, hiring an employee was all about conducting interviews, issuing offer letters, and waiting for the employee to join. Period. It was one of the several transacations that an organization did. Today, organizations are reinventing the process. Hiring is not just about offer letters and waiting for the employee to join. It is about providing a great experience for the employees right from the time they reach out to an organization for a job. It is about providing a memorable experience through all the rounds of interviews, and having an engaging ongoing conversation till the time the employee joins the organization. It is also about providing a great onboarding experience and making sure the employee is well and truly integrated with the organization."],
    "teams": ["Hierarchy to Teams", 
              "The era of several layers of management is slowly coming to an end.Organizations are slowly moving to becoming flatter where employees have the freedom to choose the project they are working on. The focus is on teams where a leader is not just someone who reports status, gives feedback, and assigns targets, but is actively involved in the work that they do. The concept of squads and tribes in Spotify and the concept of a flat organization in Valve are examples of this."],
    "outcomes": ["Timesheets to Effort & Outcomes", 
                 "Punch in the time that you come in, and punch in the time that you go out - that was meant for shopfloors. In the knowledge economy, where the calls for flexibility is getting louder and the ideas of a 4-day workweek and remote work are gaining prominence, time is not the key factor anymore. The bosses favourite is not someone who comes in early and stays late. It is the efforts and outcomes that matter."],
    "partners": ["Resources to Partners", 
                 "Machines are resources. Humans are not resources. Machines do not have emotions and can be measured in terms of efficiency and effectives. Humans have emotions and they should be rewarded for their skills and contributions. Many organizations still consider humans as resources, but many organizations are changing that. Right from not calling their people as employees, organizations are actively considering their people as partners in their journey forward."],
    "rewards": ["Wages and Bonuses to Total Rewards", 
               "The concept of wages and bonuses are a byproduct of the industrial era where people were paid based on the output they achieved. In the knowledge economy, the people want a more comprehensive reward mechanism which is not just monetary but also includes several other aspects that consider their aspirations, and concerns. ESOPs, Wellness packages, insurance benefits for family members are all such examples. People do not want only salary. They want total rewards that cater to all the levels of Maslow's hierarchy."],
    "growth": ["Promotions to Growth & Mastery", 
               "Work well and get promoted. Put in your best efforts and get promoted. That era is gone. As organizations are getting flatter, it is becoming tougher to promote people. And hence promotions have changed. Today, many organizations are recognizing people for their mastery and are helping them grow in their jobs even if it means that there is no traditional promotion."],
    "openness": ["Secrecy to Openness", 
                 "The old organizations were categorized by silos. Information was closely guarded. The people hardly knew anything. Today's organizations are changing gradually. They are slowly opening up. Organizations are moving towards a more inclusive approach where information is not withheld and data is shared to everyone. Some organizations are openly sharing all the information - including organization and team performance data across the organization as they believe that this will increase trust and accountability within the organization."],
    "worklife": ["Work-life Balance to Work-life Integration", 
                 "The traditional 9-to-5 way of working is dead. With the spread of mobile phones, people are always connected and that has meant that work follows most of these people along with their phone. This, along with an increased work load has meant that most of us are working longer than ever and people are complaining of facing burnout and other health issues. Some organizations have realized this and are actively taking steps to help people balance their work-life, or in other words integrate their professional lives with their personal lives."],
    "agility": ["Rigidity to Agility", 
                "3-year plans, 5-year plans, and even 10-year plans. And sometimes 50-year plans. This is what organizations made a couple of decades ago. Now, in a world which is changing with each passing day, it may not be possible, and it may not be appropriate. Organizations have realized this and becoming more agile. They are getting out of their business formals and adopting a more casual approach towards planning and execution. Agility is in, Rigidity is out. Plans are being made for a shorter time frame, with an open mind. Change is the only constant."],
    "delight": ["Maximum Profit to Optimum Delight", 
                "'The goal on an organization is to provide maximum profit to its stakeholders' - A maxim taught in several B-schools and a maxim that is the most inaccurate. As organizations are becoming increasingly interconnected with the outside world, the number of stakeholders who have a say on how an organization should distribute its profits, and the way organizations should act is increasing. It is not just the shareholders who have a voice. Employees, Regulatory Bodies, Partners, and the Community that the organization operates in - all are stakeholders who have a voice in the organization. Here, it is not a case of maximization, but a case of optimization."]
}

module.exports = themes;
